# SOPS configuration for secrets management
keys:
  - &netbox01 age15qrrj7ehlp5dv7l0zjf4z8tq9earwg7ecekseemhe7k6e29vr9hsx09pae  # netbox-01 (bootstrap key)

creation_rules:
  - path_regex: ^secrets/prod\.ya?ml$
    key_groups:
      - age:
          - *netbox01
    # keep everything encrypted; no plaintext fields
