creation_rules:
- path_regex: ^secrets/prod\.ya?ml$
  age: age1ycfwrad25wrjguqx4um7mck9s0xxc90dd4uytcz68wz2kcf3n4gqjejqhz,age1fzfm3rtt7pz53c95dvcup3fwh6gfdmupjgvt6wlsxg333fhzt3vshq6l5f,age12yta7yn8cc7c9nqwnvlhkhlywzvtgup0fnsu662sgkcg93grc9eqtrz7pq,age12yta7yn8cc7c9nqwnvlhkhlywzvtgup0fnsu662sgkcg93grc9eqtrz7pq
