# SOPS configuration for secrets management
creation_rules:
  - path_regex: ^secrets/prod\.ya?ml$
    age:
      - age1tkw3zel7u2l05szgppd6vc0nzxk9hpqmqfeulgphncja7aqmtups49jsrz  # netbox-01 (new key)
    # keep everything encrypted; no plaintext fields
