#!/usr/bin/env bash
# Generate a new Age key for netbox-01
set -euo pipefail

echo "🔑 Generate NetBox Age Key"
echo "=========================="
echo ""
echo "This script will help you generate a new Age key for your netbox-01 server."
echo ""
echo "Run these commands on your netbox-01 server:"
echo ""
echo "  # Create the sops-nix directory"
echo "  install -d -m 0700 /var/lib/sops-nix"
echo ""
echo "  # Generate a new Age key for this server"
echo "  nix shell nixpkgs#age -c age-keygen -o /var/lib/sops-nix/key.txt"
echo ""
echo "  # Print the public key (copy this line that starts with age1...)"
echo "  nix shell nixpkgs#age -c age-keygen -y /var/lib/sops-nix/key.txt"
echo ""
echo "After generating the key:"
echo "  1. Copy the 'age1...' public key from the output"
echo "  2. Give it to your coding agent to update the configuration"
echo "  3. The agent will re-encrypt secrets with your new key"
echo "  4. Rebuild netbox-01 with: sudo nixos-rebuild switch --flake .#netbox-01"
echo ""
echo "This ensures each server has its own unique Age key for security."
