#!/usr/bin/env bash
# Bootstrap script to copy the Age key to netbox-01
set -euo pipefail

echo "🔑 Bootstrap Age Key Setup"
echo "=========================="
echo ""
echo "This script will help you set up the Age key on your netbox-01 server."
echo ""
echo "Bootstrap Age Key: age15qrrj7ehlp5dv7l0zjf4z8tq9earwg7ecekseemhe7k6e29vr9hsx09pae"
echo ""
echo "Run these commands on your netbox-01 server:"
echo ""
echo "  # Become root"
echo "  sudo -i"
echo ""
echo "  # Create the sops-nix directory"
echo "  install -d -m 0700 /var/lib/sops-nix"
echo ""
echo "  # Copy the bootstrap key (paste this entire block):"
echo "  cat > /var/lib/sops-nix/key.txt << 'EOF'"
cat /tmp/bootstrap-age-key.txt
echo "EOF"
echo ""
echo "  # Set correct permissions"
echo "  chmod 600 /var/lib/sops-nix/key.txt"
echo ""
echo "  # Verify the key works"
echo "  age-keygen -y /var/lib/sops-nix/key.txt"
echo ""
echo "After running these commands, you can build netbox-01 with:"
echo "  sudo nixos-rebuild switch --flake /path/to/flakes#netbox-01"
echo ""
echo "The server will be able to decrypt the secrets using this bootstrap key."
