apiVersion: v1
kind: Pod
metadata:
  name: wekan
  labels:
    app: wekan
spec:
  containers:
  - name: wekan
    image: wekanteam/wekan:latest
    ports:
    - containerPort: 8080
    env:
    - name: ROOT_URL
      value: "http://localhost:8080"
    - name: MONGO_URL
      value: "mongodb://127.0.0.1:27017/wekan"
  - name: mongodb
    image: mongo:4.4
    ports:
    - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: wekan
spec:
  selector:
    app: wekan
  ports:
  - port: 8080
    targetPort: 8080
  type: LoadBalancer
