# ---- Minimal set for current NetBox build ----
postgres-password: "netbox123"

# The rest aren't used by your current NetBox bring-up, but sops-nix
# will try to materialize them since they're declared in profiles/sops.nix.
# Use placeholders for now; you can replace later.

netbox-api-key: "unused-for-now"
keycloak-admin-password: "unused-for-now"

ssl-cert: |
  -----BEGIN CERTIFICATE-----
  (placeholder)
  -----END CERTIFICATE-----

ssl-key: |
  -----BEGIN PRIVATE KEY-----
  (placeholder)
  -----END PRIVATE KEY-----

netbox-backup-private-key: |
  -----BEGIN OPENSSH PRIVATE KEY-----
  (placeholder)
  -----END OPENSSH PRIVATE KEY-----
